spring:
  application:
    name: cloudlink-user
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
    username: root
    password: tianfeifei
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
