spring:
  application:
    name: gateway
  redis:
    host: 192.168.100.49
    port: 6379
    password: 111111
    database: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8050

zuul:
  # 忽略敏感头(例如header, cookie...)
  sensitive-headers:
